# Generated by Django 2.2.4 on 2020-02-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamamsazehFa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postfa',
            name='promo',
        ),
    ]
