# Generated by Django 2.2.4 on 2020-02-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='articles/')),
                ('author', models.CharField(blank=True, default='unknown', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='articles/')),
                ('text', models.CharField(blank=True, max_length=100000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('image_name', models.CharField(default='image', max_length=300)),
                ('promo', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('info', models.TextField(blank=True)),
                ('genre', models.CharField(choices=[('1', 'Oil, Gas and Petrochemical'), ('2', 'Educational and Cultural Structures'), ('3', 'Steal Structures and Bridges'), ('4', 'Industrial and Civil Structure'), ('5', 'Mass production'), ('6', 'Road construction'), ('7', 'Others')], default='7', max_length=2)),
                ('isImportant', models.BooleanField(blank=True)),
                ('Album', models.ManyToManyField(blank=True, to='tamamsazeh.ProjectImage')),
            ],
        ),
    ]
