# Generated by Django 2.2.4 on 2020-02-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamamsazeh', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='promo',
            new_name='isPromo',
        ),
    ]
